# Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [1]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(2,6)


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a.reshape(-1,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(2,-1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(12,-1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

    Нет

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
a = np.random.randn(3,4)
a


array([[-2.14909631,  1.26386989, -0.7703484 ,  1.36582269],
       [ 0.97463874,  1.3886659 ,  0.3205679 ,  1.55647152],
       [-0.73843563,  2.27138643,  0.10581677, -0.95674122]])

In [14]:
b = a.flatten()
b

array([-2.14909631,  1.26386989, -0.7703484 ,  1.36582269,  0.97463874,
        1.3886659 ,  0.3205679 ,  1.55647152, -0.73843563,  2.27138643,
        0.10581677, -0.95674122])

In [15]:
a.size == b.size

True

In [16]:
a.shape, b.shape

((3, 4), (12,))

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.<br> Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.<br> В чем разница между массивами a и b?

In [17]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [18]:
a.shape

(10,)

In [19]:
b = np.arange(20,1,-2).reshape((1,10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [20]:
b.shape

(1, 10)

    Массив a - одномерный массив, в нем один индекс a.shape = (10,)
    Массив b - двумерный массив, в нем два индекса b.shape = (1, 10) 

#### 7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [21]:
a = np.zeros((2,2), dtype=int)
a

array([[0, 0],
       [0, 0]])

In [22]:
b = np.ones((3,2), dtype=int)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [23]:
v = np.vstack((a,b))
v

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [24]:
v.size

10

#### 8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.<br> Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов..<br> Получить матрицу At путем транспонирования матрицы A..<br> Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения..<br> Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [28]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

    Размер матрицы B - 4 строки, 4 столбца:

In [29]:
B.shape

(4, 4)


    Вычислить обратную матрицу для матрицы B не получится, потому как матрица B вырожденная:

In [30]:
np.linalg.det(B)

0.0

#### 9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.<br> Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно.<br> Поменяйте его форму так, чтобы получилась квадратная матрица C.<br> Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.<br> Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [31]:
np.random.seed(42)
c = np.random.randint(0,16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [32]:
C = c.reshape((int(np.sqrt(c.size)), -1)) 
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [33]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

    Определитель:

In [34]:
np.linalg.det(D)

-28511999.999999944

    Ранг:

In [35]:
np.linalg.matrix_rank(D)

4

    Обратная матрица:

In [36]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### 10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.<br> Убедитесь, что в матрице D_inv остались только нули и единицы.<br> С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.<br> Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [37]:
D_inv[np.where(D_inv < 0)] = 0
D_inv[np.where(D_inv > 0)] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [38]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [39]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [40]:
E = np.where(D_inv, B,C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

# Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [41]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape((2,5)).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [42]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Задание 3
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [43]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [44]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [45]:
a_centered_sp / (a.shape[0] - 1)

2.0

# * Задание 5
Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Ссылка
<br>В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [46]:
np.cov(a.T)[0,1]

2.0